Game logic feature
SuyashFowdar/tic_tac_toe pull request #3
Opened 2020-11-23 14:41 UTC by krishnzzz

## Tasks done within feature

- Divide all logics in classes
- Add methods for each class
- Put each class in separate file
- Implement the winning logic

Thank You.

2020-11-23 16:41 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @krishnzzz  and @ArreyTabe  . Thanks for submitting you project!

Great thing this project has and has done well:
:100: The game as for user names
:100: The game ends when it finds a winner
:100: The game ends when is a draw
:100: Switched between player turns

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The game exits and throws an error when invalid input is entered:
`check_valid_move': no implicit conversion from nil to integer (TypeError)`

- [ ] The game doesn't throw a message notifying the game is a draw.

- [ ] There should be no puts/print outside `bin/main`. See inline comments.

- [x] Use accessor methods. See inline comments.


### [OPTIONAL]  :yellow_circle:  

- [ ] The game should check the player's name input. Right now the game can be played without none of the player's names, making it difficult to follow the turns of each round of the game.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +  end
- [ ] There should be no puts/print outside `bin/main`

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +      puts
- [ ] There should be no puts/print outside `bin/main`

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +      puts
- [ ] There should be no puts/print outside `bin/main`

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +    puts "#{@current_player.fetch_name} has won the game!"
- [ ] There should be no puts/print outside `bin/main`

2020-11-23 16:41 UTC, jubaan commented on lib/player.rb
> +end
- [ ] Use accessor methods for `@name` and `@symbol`

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +    puts 'Game Over!'
- [ ] There should be no puts/print outside `bin/main`

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +  end
- [ ] Use descriptive and meaningful names for methods.

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +  end
- [ ] Use descriptive and meaningful names for methods.

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +  end
- [ ] Use accessor methods.

2020-11-23 16:41 UTC, jubaan commented on lib/game.rb
> +  end
- [ ] Use accessor methods.

2020-11-24 12:37 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @krishnzzz  and @ArreyTabe ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-11-24 12:43 UTC, merged